spring.application.name=QREventSystem
spring.datasource.url=jdbc:mysql://localhost:3306/QR_Event_DB
spring.datasource.username=root
spring.datasource.password=percy

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

